### ISSUE TITLE
Improve build output so that it shows addition file info

### ISSUE THREAD

**Issue by vividviolet** [Shopify/shopify-cli-extensions#91]
**Current**

```
┃ 🔭 > Starting production build
┃ 🔭 > Build completed successfully
┃ 🔭 > size: 106 kB / gzip: 33.3 kB / brotli: 28.8 kB
┃ Done in 6.75s.
```

**New**
```
Build was successful!
```

Esbuild is outputting additional info to standard out but we're not displaying these messages

```
build/main.js            99.9kb
build/main.js.LEGAL.txt   1.0kb
✨  Done in 0.55s.
```

**Comment by t6d** [comment]
Which of these messages should we retain?

<img width="808" alt="Screen Shot 2021-11-01 at 11 09 53 AM" src="https://user-images.githubusercontent.com/77060/139694517-4f7b438c-58a2-43f2-a501-22f61e0e39b3.png">

**Comment by vividviolet** [comment]
I think we should pick either "Build was successful!" or the Go server message.

I like the Go server message but developers are not really exposed to the uuid so they wouldn't know what it means. Should we display the title instead?

We should keep `build/main.js 263b` since we currently impose a file size limit. Is there a way to get the gzip size from esbuild?

**Comment by t6d** [comment]
Good idea, let's replace the UUID with the title.

Next question, should the Go server or the Ruby CLI generate the log message? The `build/main.js` portion obviously has to come from ESBuild. Making the Go server responsible is a bit easier because we have to otherwise implement the same log grouping on the Ruby side that we already have in Go. However, should we ever translate this content, doing it on the Go side would be more complicated.

I'm advocating for making the Go side responsible for now as a multi-language support for the CLI is not an immediate goal.

**Comment by vividviolet** [comment]
> I'm advocating for making the Go side responsible for now as a multi-language support for the CLI is not an immediate goal.

Makes sense to me. I'm good with this plan

**Comment by t6d** [comment]
The latest iteration of the Go code has already improved to show better status messages:

```
2022-first-test

  build/main.js  263b

Build succeeded
```

It now displays the name of the extension, the affected files as well as the build status.

I'll log a nice to have ticket that improves the visualization of the the extension name a bit more so that in the even of multiple extensions the grouping of messages is a bit more apparent. But if necessary, this can ship as is as there is no longer a duplication of information and all details are being forwarded to the user.
